name: Test and coverage

on:
  push:
    paths:
      - '**.go'
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: go get
        run: go get ./...

      - name: go mod tidy
        run: go mod tidy

      - name: Run coverage
        run: go test -v -race -coverprofile="coverage.out" -covermode=atomic ./...

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
