name: Test and coverage

on:
  push:
    paths:
      - '**.go'
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.18

      - name: install vault
        run: |
          curl -O https://releases.hashicorp.com/vault/1.13.0/vault_1.13.0_linux_amd64.zip
          unzip vault_1.13.0_linux_amd64.zip
          sudo mv vault /usr/bin/.
          mkdir assets/raft
          vault server -config assets/vault-cfg.hcl &

      - name: go get
        run: go get ./...

      - name: go mod tidy
        run: go mod tidy

      - name: Run coverage
        run: go test -v -race -coverprofile="coverage.out" -covermode=atomic ./...

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
